---

- name: install apache and upload web page
  hosts: all
  become: yes
  
  vars:
    source_file: ./WebSite/index.html
    destin_file: /var/www/html

  tasks:
  - name: install apache web server
    apt: name=apache2 state=latest

  - name: copy WebPage to server
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart apache

  - name: start web server and enable it on boot
    service: name=apache2 state=started enabled=yes
 
  handlers:
  - name: Restart apache
    service: name=apache2 state=restarted

...
